export const data = {
  data: {
    getModeratorMeetings: [
      {
        id: "c140228f-74bd-4302-a118-ef863c2cccff",
        title: "Corp Commander Conference",
        startTime: null,
        slug: "556-487-815",
        type: "BAR",
        status: "Active",
        attendees: [
          {
            firstName: "Nouman",
            lastName: "Nadeem",
            email: "nn@gmail.com",
            __typename: "Attendee",
          },
          {
            firstName: "Usman",
            lastName: "Zaheer",
            email: "uz@gmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "8dde468a-c84f-453d-ad1e-3f8ed5565a1f",
        title: "Meeting - Attendee",
        startTime: null,
        slug: "297-617-995",
        type: "BAR",
        status: "Active",
        attendees: [
          {
            firstName: "Taqi",
            lastName: "Mustafa",
            email: "taqi.mustafa@hotmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "301e8bb5-5f32-4d5a-964c-0b29f3a6f897",
        title: "Mic Test",
        startTime: null,
        slug: "957-435-649",
        type: "BAR",
        status: "Active",
        attendees: [
          {
            firstName: "Haseeb",
            lastName: "Rehman",
            email: "hu@gmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "4b1fb10f-73f2-44b4-bfe6-78600081e0d1",
        title: "Meeting 1on1 - Haseeb",
        startTime: null,
        slug: "384-557-515",
        type: "BAR",
        status: "Active",
        attendees: [
          {
            firstName: "Haseeb",
            lastName: "Rehman",
            email: "ihaseeb98@gmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "d7d1c11f-7fbe-410d-824b-572b971079d2",
        title: "Bar",
        startTime: null,
        slug: "514-426-829",
        type: "BAR",
        status: "Active",
        attendees: [
          {
            firstName: "Taqi",
            lastName: "Mustafa",
            email: "taqi.mustafa@hotmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "e3326477-1e0d-41a3-a331-5f9518170973",
        title: "Test - Email",
        startTime: null,
        slug: "665-671-555",
        type: "BAR",
        status: "Active",
        attendees: [
          {
            firstName: "",
            lastName: "",
            email: "taqi.mustafa08@gmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "b8975c7c-a276-450d-bf9e-f4163cf42cea",
        title: "Test - Email 1",
        startTime: null,
        slug: "173-973-451",
        type: "CAFE",
        status: "Active",
        attendees: [
          {
            firstName: "",
            lastName: "",
            email: "taqi.mustafa08@gmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "d0e3ed2b-9ccc-45b1-8815-46839bc89261",
        title: "Email Test",
        startTime: null,
        slug: "918-977-223",
        type: "CAFE",
        status: "Active",
        attendees: [
          {
            firstName: "Taqi",
            lastName: "Mustafa",
            email: "taqi.mustafa@hotmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "430056a3-a7e6-4290-add9-0d81f3f74d8d",
        title: "Meeting - Email Invitation",
        startTime: null,
        slug: "905-275-912",
        type: "CAFE",
        status: "Active",
        attendees: [
          {
            firstName: "Taqi",
            lastName: "Mustafa",
            email: "taqi@tame.events",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "e0f7b557-f921-4f63-b209-cf7791349f13",
        title: "Gmail Email Test",
        startTime: null,
        slug: "996-423-755",
        type: "CAFE",
        status: "Active",
        attendees: [
          {
            firstName: "",
            lastName: "",
            email: "taqi.mustafa08@gmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "b9d474df-7636-4d98-a476-81051a87083c",
        title: "Meeting - April 29th",
        startTime: null,
        slug: "421-519-943",
        type: "BAR",
        status: "Active",
        attendees: [
          {
            firstName: "Taqi",
            lastName: "Mustafa",
            email: "taqi.mustafa@hotmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "18aa8da1-7376-45e7-ba45-0c0015e8d72c",
        title: "Stage - Meeting",
        startTime: null,
        slug: "702-608-372",
        type: "CAFE",
        status: "Active",
        attendees: [
          {
            firstName: "Taqi",
            lastName: "Mustafa",
            email: "taqi.mustafa@hotmail.com",
            __typename: "Attendee",
          },
          {
            firstName: "Taqi",
            lastName: "Mustafa",
            email: "tm@gmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "bc89fd4e-d666-45a4-97bf-31c2ac9ebf67",
        title: "Lounge - Meeting",
        startTime: null,
        slug: "650-225-151",
        type: "LOBBY",
        status: "Active",
        attendees: [
          {
            firstName: "Taqi",
            lastName: "Mustafa",
            email: "taqi.mustafa@hotmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "c03252f1-6c6d-4106-9071-13d319f9a5f3",
        title: "New Cafe",
        startTime: null,
        slug: "766-861-782",
        type: "CAFE",
        status: "Active",
        attendees: [
          {
            firstName: "Taqi",
            lastName: "Mustafa",
            email: "taqi.mustafa@hotmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "febfcb6b-c29e-4025-9a4b-a036d41e4585",
        title: "Attendee Subscription",
        startTime: null,
        slug: "669-501-438",
        type: "CAFE",
        status: "Active",
        attendees: [
          {
            firstName: "Taqi",
            lastName: "Mustafa",
            email: "taqi.mustafa@hotmail.com",
            __typename: "Attendee",
          },
          {
            firstName: "Taqi",
            lastName: "Mustafa",
            email: "tm@gmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "8769aa29-b487-46e2-8c63-4ae9b3f3446e",
        title: "Some meeting that was made for testing!",
        startTime: null,
        slug: "time-zone",
        type: "DEFAULT",
        status: "Active",
        attendees: [
          {
            firstName: "Nouman",
            lastName: "Nadeem",
            email: "nn@gmail.com",
            __typename: "Attendee",
          },
          {
            firstName: "Taqi",
            lastName: "Mustafa",
            email: "tm@gmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "220c1beb-5d62-43ff-8c86-3d35e7d23fa6",
        title: "Timezone - Test",
        startTime: null,
        slug: "319-965-217",
        type: "CAFE",
        status: "Active",
        attendees: [
          {
            firstName: "Taqi",
            lastName: "Mustafa",
            email: "taqi.mustafa@hotmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "6899d324-066f-497d-b91e-fe13a635b2ea",
        title: "Avatar Test",
        startTime: null,
        slug: "796-670-906",
        type: "CAFE",
        status: "Active",
        attendees: [
          {
            firstName: "Taqi",
            lastName: "Mustafa",
            email: "taqi.mustafa@hotmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "af56c465-6b98-4311-ad33-4f1a5e606848",
        title: "Avatar Test 1",
        startTime: null,
        slug: "130-752-162",
        type: "BAR",
        status: "Active",
        attendees: [
          {
            firstName: "Taqi",
            lastName: "Mustafa",
            email: "taqi.mustafa@hotmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "e966bc63-6375-4086-807b-2cb9f7e10c05",
        title: "Avatar Test 3",
        startTime: null,
        slug: "691-101-787",
        type: "BAR",
        status: "Active",
        attendees: [
          {
            firstName: "Taqi",
            lastName: "Mustafa 1",
            email: "taqi.mustafa+1@hotmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "aa077e15-7e8e-4b6f-92b9-5022592187ac",
        title: "Showroom Waiting",
        startTime: null,
        slug: "834-311-283",
        type: "SHOWROOM",
        status: "Active",
        attendees: [
          {
            firstName: "Taqi",
            lastName: "Mustafa",
            email: "taqi.mustafa@hotmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "447a7a65-2d9c-44e3-a6cd-ae96d2f6f8cb",
        title: "Lobby - New",
        startTime: null,
        slug: "908-104-134",
        type: "CAFE",
        status: "Active",
        attendees: [
          {
            firstName: "Taqi",
            lastName: "Mustafa",
            email: "taqi.mustafa@hotmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "6cbaa223-7c59-4cf5-b2a4-a02d76e46a43",
        title: "Meeting - Last name",
        startTime: "1621340648000",
        slug: "520-172-446",
        type: "CAFE",
        status: "Active",
        attendees: [
          {
            firstName: "Taqi",
            lastName: "Mustafa",
            email: "taqi.mustafa@hotmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "11ab9bf7-e60c-4858-b2f6-48344f0d8e80",
        title: "Meeting",
        startTime: "1621399782000",
        slug: "148-272-622",
        type: "CAFE",
        status: "Active",
        attendees: [
          {
            firstName: "Taqi",
            lastName: "Mustafa",
            email: "taqi.mustafa@hotmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "fde079ec-6e73-4f25-9cda-4fee50894adf",
        title: "New Waiting Room 2",
        startTime: "1622473168000",
        slug: "321-554-452",
        type: "BAR",
        status: "Rescheduled",
        attendees: [
          {
            firstName: "Taqi",
            lastName: "Mustafa",
            email: "taqi.mustafa@hotmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
      {
        id: "ee65310e-779c-4bb9-b680-81280d42d31f", //cur.id = cur
        title: "New Meeting",
        startTime: "1622090480000",
        slug: "749-792-581",
        type: "BAR",
        status: "Active",
        attendees: [
          {
            firstName: "Taqi",
            lastName: "Mustafa",
            email: "taqi.mustafa@hotmail.com",
            __typename: "Attendee",
          },
          {
            firstName: "",
            lastName: "",
            email: "taqi.mustafa08@gmail.com",
            __typename: "Attendee",
          },
        ],
        reschedules: [],
        __typename: "Meeting",
      },
    ],
  },
};

const reducer = (acc, cur) => {
  return { ...acc, [cur.id]: cur };
};

let newgetModeratorMeetings = data.data.getModeratorMeetings.reduce(
  reducer,
  {}
);
console.log(newgetModeratorMeetings);
